commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - edumorrow-k8s/edumorrow-deployment.yml
  - edumorrow-k8s/edumorrow-service.yml
  - edumorrow-k8s/edumorrow-mongodb.yml
  - edumorrow-k8s/edumorrow-elasticsearch.yml
  # messagebroker
  - messagebroker-k8s/kafka.yml
  # monitoring elk
  - console-k8s/jhipster-elasticsearch.yml
  - console-k8s/jhipster-logstash.yml
  - console-k8s/jhipster-console.yml
  - console-k8s/jhipster-dashboard-console.yml
  - console-k8s/jhipster-zipkin.yml
  # service discovery eureka/consul
  - registry-k8s/jhipster-registry.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
