apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: gcr.io/edumorrow/edumorrow
      context: ../Edumorrow
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
